console.log('🔍 Trouver le mot de passe PostgreSQL Supabase')
console.log('')
console.log('📍 Aller sur le dashboard:')
console.log('https://supabase.com/dashboard/project/wodyrsasfqfoqdydrfew/settings/database')
console.log('')
console.log('🔧 Dans la page Database Settings, chercher:')
console.log('')
console.log('1️⃣ Section "Connection parameters" ou "Database"')
console.log('   - Host: db.wodyrsasfqfoqdydrfew.supabase.co')
console.log('   - Database: postgres')
console.log('   - User: postgres.wodyrsasfqfoqdydrfew')
console.log('   - Password: [CHERCHER CE MOT DE PASSE]')
console.log('')
console.log('2️⃣ Ou section "Connection string"')
console.log('   - URI: postgresql://postgres.wodyrsasfqfoqdydrfew:PASSWORD@...')
console.log('')
console.log('3️⃣ Si pas visible, chercher "Reset database password" ou "Show password"')
console.log('')
console.log('🎯 Le mot de passe ressemble à:')
console.log('   - Une chaîne aléatoire comme: kX9mP2vR8qL5nW7tY3zA')
console.log('   - OU celui que vous avez défini lors de la création')
console.log('')
console.log('💡 Alternative: Créer un nouveau mot de passe depuis le dashboard')
