console.log('🔗 Configuration Supabase pour ACGE')
console.log('')
console.log('📋 Dashboard Supabase:')
console.log('https://supabase.com/dashboard/project/wodyrsasfqfoqdydrfew/settings/database')
console.log('')
console.log('🔧 Instructions:')
console.log('1. Ouvrir le lien ci-dessus')
console.log('2. Chercher "Connection string" ou "URI"')
console.log('3. Copier l\'URL PostgreSQL qui ressemble à:')
console.log('   postgresql://postgres.wodyrsasfqfoqdydrfew:[PASSWORD]@aws-0-eu-west-3.pooler.supabase.com:5432/postgres')
console.log('')
console.log('4. Exécuter:')
console.log('   vercel env add DATABASE_URL production')
console.log('   (coller l\'URL sans guillemets)')
console.log('')
console.log('5. Redéployer:')
console.log('   vercel --prod')
